create table if not exists public.products (
  firestore_document_id text primary key,
  customer_id text,
  customer_name text,
  item_name text,
  artwork_no text,
  length numeric,
  width numeric,
  height numeric,
  color text,
  reel_size numeric,
  cut_size numeric,
  ply numeric,
  flute text,
  pin_pasting text,
  pin_type text,
  pin_qty numeric,
  creasing text,
  ups numeric,
  packing text,
  special_requirement text,
  actual_costing numeric,
  layers jsonb,
  is_archived boolean,
  created_by text,
  updated_by text,
  created_at timestamptz,
  updated_at timestamptz,
  raw_data jsonb not null,
  imported_at timestamptz not null default now(),
  synced_at timestamptz not null default now()
);
